### ISSUE TITLE
make install fails on 'introduction.rst'

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#416] opened 2020-11-03 01:36 UTC
With a user version, if I run cmake+make+make install, I get

<pre>
-- Installing: /tmp/j/bin/GudhUI
/usr/lib/python3.8/distutils/extension.py:131: UserWarning: Unknown Extension options: 'cython_directives'
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/glisse/repos/gudhi3/build/2/build/python/setup.py", line 68, in <module>
    with open("introduction.rst", "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'introduction.rst'
</pre>

**Comment by mglisse** [comment] 2020-11-04 07:00
The patch using a full path was good, even if it isn't sufficient to make `make install` work reliably. But if we remove python from `make install`, then it may be unnecessary.

**Comment by LutzWeischerFujitsu** [comment] 2021-03-17 08:39
... it's still there, on AArch64, Fedora 33: 
... 
-- Installing: /usr/local/bin/sparse_rips_persistence
/usr/lib64/python3.9/distutils/extension.py:131: UserWarning: Unknown Extension options: 'cython_directives'
  warnings.warn(msg)
Traceback (most recent call last):
  File "/data/jw/gudhi/build/src/python/setup.py", line 68, in <module>
    with open("introduction.rst", "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'introduction.rst'
[jw@cn06 build]$

**Comment by VincentRouvreau** [comment] 2021-03-17 10:21
@LutzWeischerFujitsu Do you have any 'introduction.rst' file in your folder '/data/jw/gudhi/build/src/python/' ?
If this is the case, please launch `make python` (or `python setup.py build_ext --inplace`) command from this directory.
If not, you can replace in  '/data/jw/gudhi/build/src/python/setup.py' file:
```python
# read the contents of introduction.rst
with open("introduction.rst", "r") as fh:
    long_description = fh.read()
```
with:
```python
long_description = ''
```
These lines are just here to make a nice project description for [pypi gudhi project](https://pypi.org/project/gudhi/).
Sorry for the inconvenience.

**Comment by LutzWeischerFujitsu** [comment] 2021-03-17 13:26
All recommendations failed.

**Comment by VincentRouvreau** [comment] 2021-03-19 10:44
@LutzWeischerFujitsu
I manage to install gudhi on a Fedora 33 thanks to [this Dockerfile](https://gist.github.com/VincentRouvreau/51417f773363edfd12ef73fcbc6fc219), if it can help you.

I was also wandering to know what was your error message after removing the lines opening the 'introduction.rst' in the setup.py file.

**Comment by LutzWeischerFujitsu** [comment] 2021-03-23 07:42
I restarted from scratch to answer your question, but ran into this error: 

(base) [jw@cn06 build]$ cmake -DCMAKE_BUILD_TYPE=Release -DWITH_GUIDE_EXAMPLE=ON ..
-- GUDHI version : 3.5.0rc1
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/lib64/ccache/c++ compiler.
-- Boost include dirs: /usr/include
-- Boost libraries:
-- Using gcc version 4 or later. Adding -frounding-math
-- CGAL version: 5.1.2.
-- Build type: Release
-- USING CXXFLAGS = ' -O2 -DNDEBUG'
-- USING EXEFLAGS = ' '
-- Requested component: MPFR
-- Requested component: GMPXX
-- Requested component: GMP
-- Found Intel TBB
TBB found in /usr/local/lib64
gprof found in /usr/bin/gprof
diff found in /usr/bin/diff
gnuplot found in /usr/bin/gnuplot
-- boost include dirs:/usr/include
-- boost library dirs:/usr/lib64
PYTHON_MODULE_NAME = cython
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cython'

PYTHON_MODULE_NAME = pytest
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pytest'

PYTHON_MODULE_NAME = matplotlib
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'matplotlib'

++ Python module numpy - Version 1.20.1  found
PYTHON_MODULE_NAME = scipy
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'

PYTHON_MODULE_NAME = sphinx
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sphinx'

PYTHON_MODULE_NAME = sklearn
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sklearn'

PYTHON_MODULE_NAME = ot
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ot'

PYTHON_MODULE_NAME = pybind11
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pybind11'

PYTHON_MODULE_NAME = torch
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'

PYTHON_MODULE_NAME = pykeops
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pykeops'

PYTHON_MODULE_NAME = eagerpy
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'eagerpy'

PYTHON_MODULE_NAME = hnswlib
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'hnswlib'

PYTHON_MODULE_NAME = tensorflow
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'

++ Release compilation flags are:  -Wall -pedantic -O2 -DNDEBUG
++ GUDHI_SUB_DIRECTORIES list is:";test;utilities"
CMake Warning (dev) at /usr/share/cmake/Modules/FindOpenGL.cmake:305 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib64/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib64/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib64/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  src/GudhUI/CMakeLists.txt:4 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

++ GudhUI will not be compiled because Qt5 COMPONENTS Widgets Xml OpenGL are not found
++ Python module will not be compiled because cython was not found
++ GUDHI_MODULES list is:"common;Alpha_complex;Bitmap_cubical_complex;Bottleneck_distance;Collapse;Contraction;Cech_complex;Hasse_complex;Persistence_representations;Persistent_cohomology;Rips_complex;Simplex_tree;Skeleton_blocker;Spatial_searching;Subsampling;Tangential_complex;Toplex_map;Witness_complex;Nerve_GIC;cpp-documentation"
++ GUDHI_MISSING_MODULES list is:"GudhUI;python"
-- Configuring done
-- Generating done
-- Build files have been written to: /data/jw/gudhi/build
(base) [jw@cn06 build]$ pip3 install cython
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cython in /home/jw/.local/lib/python3.9/site-packages (0.29.21)
WARNING: You are using pip version 20.1.1; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
(base) [jw@cn06 build]$

**Comment by mglisse** [comment] 2021-03-23 07:51
Sadly we don't seem to print the version of python detected, but I believe CMake is trying to use python 2.7 while you have cython for python 3.9.

**Comment by VincentRouvreau** [comment] 2021-03-23 08:37
Good catch @mglisse !
@LutzWeischerFujitsu  the cmake command is `cmake -DCMAKE_BUILD_TYPE=Release -DWITH_GUIDE_EXAMPLE=ON  -DPython_ADDITIONAL_VERSIONS=3 ..`

**Comment by LutzWeischerFujitsu** [comment] 2021-03-23 11:08
(base) [jw@cn06 build]$ cmake -DCMAKE_BUILD_TYPE=Release -DWITH_GUIDE_EXAMPLE=ON -DPython_ADDITIONAL_VERSIONS=3 ..
-- GUDHI version : 3.5.0rc1
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/lib64/ccache/c++ compiler.
-- Boost include dirs: /usr/include
-- Boost libraries:
-- Using gcc version 4 or later. Adding -frounding-math
-- CGAL version: 5.1.2.
-- Build type: Release
-- USING CXXFLAGS = ' -O2 -DNDEBUG'
-- USING EXEFLAGS = ' '
-- Requested component: MPFR
-- Requested component: GMPXX
-- Requested component: GMP
-- Found Intel TBB
TBB found in /usr/local/lib64
gprof found in /usr/bin/gprof
diff found in /usr/bin/diff
gnuplot found in /usr/bin/gnuplot
-- boost include dirs:/usr/include
-- boost library dirs:/usr/lib64
PYTHON_MODULE_NAME = cython
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cython'

++ Python module pytest - Version 6.2.2  found
PYTHON_MODULE_NAME = matplotlib
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'matplotlib'

++ Python module numpy - Version 1.20.1  found
PYTHON_MODULE_NAME = scipy
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'

PYTHON_MODULE_NAME = sphinx
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sphinx'

PYTHON_MODULE_NAME = sklearn
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sklearn'

PYTHON_MODULE_NAME = ot
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ot'

PYTHON_MODULE_NAME = pybind11
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pybind11'

PYTHON_MODULE_NAME = torch
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'

PYTHON_MODULE_NAME = pykeops
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pykeops'

PYTHON_MODULE_NAME = eagerpy
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'eagerpy'

PYTHON_MODULE_NAME = hnswlib
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'hnswlib'

PYTHON_MODULE_NAME = tensorflow
     - PYTHON_MODULE_RESULT = 1
     - PYTHON_MODULE_VERSION =
     - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'

++ Release compilation flags are:  -Wall -pedantic -O2 -DNDEBUG
++ GUDHI_SUB_DIRECTORIES list is:";test;utilities"
CMake Warning (dev) at /usr/share/cmake/Modules/FindOpenGL.cmake:305 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib64/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib64/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib64/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  src/GudhUI/CMakeLists.txt:4 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

++ GudhUI will not be compiled because Qt5 COMPONENTS Widgets Xml OpenGL are not found
++ Python module will not be compiled because cython was not found
++ GUDHI_MODULES list is:"common;Alpha_complex;Bitmap_cubical_complex;Bottleneck_distance;Collapse;Contraction;Cech_complex;Hasse_complex;Persistence_representations;Persistent_cohomology;Rips_complex;Simplex_tree;Skeleton_blocker;Spatial_searching;Subsampling;Tangential_complex;Toplex_map;Witness_complex;Nerve_GIC;cpp-documentation"
++ GUDHI_MISSING_MODULES list is:"GudhUI;python"
-- Configuring done
-- Generating done
-- Build files have been written to: /data/jw/gudhi/build
(base) [jw@cn06 build]$

**Comment by mglisse** [comment] 2021-03-23 11:17
Strange, here it prints
> -- Found PythonInterp: /usr/bin/python3.9 (found version "3.9.2")

before looking for cython.

Do you have something like `PYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.9` in the generated file CMakeCache.txt?

**Comment by mglisse** [comment] 2021-03-23 11:21
By the way, I am answering as if your goal was to build the python module. But from what you show you are not getting an error, just warnings telling you that because of missing dependencies, only some parts of gudhi can be built (not the python module). I don't know if that's the part you are interested in.

**Comment by LutzWeischerFujitsu** [comment] 2021-03-23 15:08
It looks like being alphabetically sorted. For Python I have only 

Python_ADDITIONAL_VERSIONS:UNINITIALIZED=3

I'm going for a fresh node installation and restart from scratch.

**Comment by mglisse** [comment] 2021-03-23 15:24
If CMakeCache.txt doesn't say anything else about python, it seems to indicate that cmake failed to find python...
Yes, it is better always to restart from scratch (and build in a different directory than the sources) since CMake keeps a cache that can interfere with successive tries.

**Comment by LutzWeischerFujitsu** [comment] 2021-04-26 13:23
Restarted fresh again and falling back onto where this issue started. The master hasn't yet been fixed?: 

[jw@cn05 build]$ sudo make VERBOSE=1 -j$(nproc) install
...
-- Up-to-date: /usr/local/bin/km.py.COPYRIGHT
Traceback (most recent call last):
  File "/data/jw/gudhi/build/src/python/setup.py", line 67, in <module>
    with open("introduction.rst", "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'introduction.rst'
[jw@cn05 build]$

**Comment by mglisse** [comment] 2021-04-26 21:58
#482 is supposed to fix it soon (by not installing the python part).

**Comment by VincentRouvreau** [comment] 2021-04-27 07:20
> #482 is supposed to fix it soon (by not installing the python part).

Because of git issue on my side, it will be #483

**Comment by VincentRouvreau** [comment] 2021-04-28 07:40
@LutzWeischerFujitsu #483 is now merged in master.
Be aware that make install will no more install the python package.
You will have to `python3 setup.py [--user] install` to install it.

**Comment by LutzWeischerFujitsu** [comment] 2021-04-28 09:44
- now tests 185, 206, 212 fail, before 79, 85 
- '/data/jw/gudhi/build/setup.py': [Errno 2] No such file or directory

**Comment by mglisse** [comment] 2021-04-28 09:55
>     * now tests 185, 206, 212 fail, before 79, 85

The numbers are not very stable, the names would be clearer, and the error messages even better.

>     * '/data/jw/gudhi/build/setup.py': [Errno 2] No such file or directory

Did that happen when you ran `python3 setup.py install`? You need to `cd python` (or `src/python`) before that.

**Comment by LutzWeischerFujitsu** [comment] 2021-04-28 11:41
The following tests FAILED:
        185 - sphinx_py_test (Failed)
        206 - rips_complex_diagram_persistence_from_distance_matrix_file_example_py_test (Failed)
        212 - test_simplex_generators_py_test (Subprocess aborted)

There is no 'python' directory under 'build'. Also no 'setup.py': 
[jw@cn05 build]$ ls
CMakeCache.txt              CMakeFiles           Testing              install_manifest.txt
CMakeDoxyfile.in            CTestTestfile.cmake  biblio               new_gudhi_version_creation.md
CMakeDoxygenDefaults.cmake  Makefile             cmake_install.cmake  src
[jw@cn05 build]$

**Comment by mglisse** [comment] 2021-04-28 12:01
> There is no 'python' directory under 'build'

That's why I said
> (or `src/python`)

whether you have one or the other depends on how you get the sources.

**Comment by mglisse** [comment] 2021-04-28 12:16
When running the tests, if instead of `make test` you call `ctest --force-new-ctest-process --output-on-failure` or if you `export CTEST_OUTPUT_ON_FAILURE=1` in your environment, you should get more useful error messages on the tests that fail, and we will have more chances to understand why they are failing.

**Comment by LutzWeischerFujitsu** [comment] 2021-04-29 06:45
The src/python part works. 

[jw@cn05 build]$ ctest --force-new-ctest-process --output-on-failure
Test project /data/jw/gudhi/build
        Start   1: Common_example_vector_double_off_reader
  1/222 Test   #1: Common_example_vector_double_off_reader .....................................................   Passed    0.01 sec
...
185/222 Test #185: sphinx_py_test ..............................................................................***Failed   12.67 sec
Running Sphinx v2.2.2

Extension error:
Could not import extension sphinx_paramlinks (exception: No module named 'sphinx_paramlinks')

        Start 186: alpha_rips_persistence_bottleneck_distance_py_test
186/222 Test #186: alpha_rips_persistence_bottleneck_distance_py_test ..........................................   Passed    1.16 sec
...
        Start 206: rips_complex_diagram_persistence_from_distance_matrix_file_example_py_test
206/222 Test #206: rips_complex_diagram_persistence_from_distance_matrix_file_example_py_test ..................***Failed    1.73 sec
Subprocess aborted
...
212/222 Test #212: test_simplex_generators_py_test .............................................................Subprocess aborted***Exception:   7.03 sec
============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /data/jw/gudhi
plugins: localserver-0.5.0, typeguard-2.10.0, anyio-2.1.0, requests-mock-1.7.0, cov-2.11.1, forked-1.3.0, xdist-1.34.0, flaky-3.7.0, mock-3.5.1, hydra-core-1.0.6, regressions-2.2.0, datadir-1.3.1
collected 3 items

../../../src/python/test/test_simplex_generators.py ..Fatal Python error: Aborted

Current thread 0x0000ffff86fc1d20 (most recent call first):
  File "/data/jw/gudhi/src/python/test/test_simplex_generators.py", line 58 in test_empty
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/python.py", line 183 in pytest_pyfunc_call
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/python.py", line 1641 in runtest
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/runner.py", line 162 in pytest_runtest_call
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/runner.py", line 255 in <lambda>
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/runner.py", line 311 in from_call
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/runner.py", line 254 in call_runtest_hook
  File "/home/jw/.local/lib/python3.9/site-packages/flaky/flaky_pytest_plugin.py", line 138 in call_and_report
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/runner.py", line 126 in runtestprotocol
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/runner.py", line 109 in pytest_runtest_protocol
  File "/home/jw/.local/lib/python3.9/site-packages/flaky/flaky_pytest_plugin.py", line 94 in pytest_runtest_protocol
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/main.py", line 348 in pytest_runtestloop
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/main.py", line 323 in _main
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/main.py", line 269 in wrap_session
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/config/__init__.py", line 162 in main
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185 in console_main
  File "/home/jw/.local/lib/python3.9/site-packages/pytest/__main__.py", line 5 in <module>
  File "/usr/lib64/python3.9/runpy.py", line 87 in _run_code
  File "/usr/lib64/python3.9/runpy.py", line 197 in _run_module_as_main
...
The following tests FAILED:
        185 - sphinx_py_test (Failed)
        206 - rips_complex_diagram_persistence_from_distance_matrix_file_example_py_test (Failed)
        212 - test_simplex_generators_py_test (Subprocess aborted)
Errors while running CTest
[jw@cn05 build]$

**Comment by mglisse** [comment] 2021-04-29 07:19
The sphinx documentation needs the python module `sphinx-paramlinks`. I filed #486 to make this dependency nicer (either an early message about something missing, or skipping this part of the build/test if the dependency is missing).

The other 2 tests don't provide much hints :-( test_simplex_generators_py_test seems to fail when computing the persistence of an empty complex (maybe throwing an uncaught exception, since it shows "Exception:"?), but rips_complex_diagram_persistence_from_distance_matrix_file_example_py_test just aborts and doesn't even have a stack trace or other message? :-(

Thanks for your patience, debugging may be hard if we cannot reproduce the errors, I'll try it on aarch64 which looks like the main originality of your setup.

**Comment by mglisse** [comment] 2021-04-29 09:28
I tried on an aarch64 system, and even with various debug modes, test_simplex_generators_py_test always passed...

**Closed** 2021-09-07 15:49 UTC
