### ISSUE TITLE
About the construction of cube complex

### ISSUE THREAD

**Issue by taoshen1** [GUDHI/gudhi-devel#1162] opened 2024-12-19 08:09 UTC
Hello, thank you for your works.
I have a question.The data I randomly constructed was  
array([[0, 2, 1, 3, 2],
       [0, 0, 2, 2, 1],
       [0, 2, 3, 3, 1],
       [0, 0, 1, 0, 3]], dtype=uint16)
Why is the persistent homology of the computation is[(0,(0.0, inf), (0,(0.0, 1.0))] ,not[(0,(0.0, inf), (0,(0.0, 1.0)),(1,(2.0,3.0))],But when my data is
array([[2, 1, 3, 2],
       [0, 2, 2, 1],
       [2, 3, 3, 1],
       [0, 1, 0, 3]], dtype=uint16)  ,the result is [(1, (2.0, 3.0)), (0, (0.0, inf)), (0, (0.0, 2.0)), (0, (0.0, 1.0))]  ,I lost my ring structure.

**Comment by mglisse** [comment] 2024-12-19 08:20
(unless the issue is specifically with the tutorials, please use gudhi-devel, I have migrated the issue there)
Hello,
could you please show the code you used to get these persistence diagrams? I tried a few options and none gave the result you mention.

**Comment by taoshen1** [comment] 2024-12-19 09:42
ok，The following is part of my code:

import gudhi
import numpy as np
from gudhi import cubical_complex

random_image=np.array([[2,1,3,2],[0,2,2,1],[2,3,3,1],[0,1,0,3]])
cubical_complexA=cubical_complex.CubicalComplex(dimensions=random_image.shape,
                                                top_dimensional_cells=random_image.flatten())
A=cubical_complexA.persistence()

new_column_0 = np.full((random_image.shape[0],1), 0, dtype=np.uint16)
random_image_with_new_column_0 = np.concatenate((new_column_0, random_image), axis=1)
cubical_complexB=cubical_complex.CubicalComplex(
    dimensions=random_image_with_new_column_0.shape,
    top_dimensional_cells=random_image_with_new_column_0.flatten())
B=cubical_complexB.persistence()

new_column_4 = np.full((random_image.shape[0],1), 4, dtype=np.uint16)
random_image_with_new_column_4 = np.concatenate((new_column_4, random_image), axis=1)
cubical_complexC=cubical_complex.CubicalComplex(
    dimensions=random_image_with_new_column_4.shape,
    top_dimensional_cells=random_image_with_new_column_4.flatten())
C=cubical_complexC.persistence()

Here, I added a column of 0 and 4 to my random_image side. When I added the '0' column, why didn't my 1-dimensional ring (2,3)? Join the '4' column, why not output [(1) (2, 3), (0, (0, 1)), (0, (0, 2)), (0, (0, inf))]
Thank you!!

> (unless the issue is specifically with the tutorials, please use gudhi-devel, I have migrated the issue there) Hello, could you please show the code you used to get these persistence diagrams? I tried a few options and none gave the result you mention.

**Comment by mglisse** [comment] 2024-12-19 12:02
> `cubical_complexA=cubical_complex.CubicalComplex(dimensions=random_image.shape,
top_dimensional_cells=random_image.flatten())`

You should use the simpler

```python
cubical_complexA=gudhi.CubicalComplex(top_dimensional_cells=random_image)
```

If you want to pass the dimensions explicitly, the code expects them in Fortran order (for historical reasons), it is much less error-prone to let it guess the dimensions from a non-flat numpy array.

(Let me also advertise the newer CubicalPersistence, which can be significantly faster in some cases)

**Comment by taoshen1** [comment] 2024-12-20 06:25
That's solved. Thank you very much

**Comment by VincentRouvreau** [comment] 2024-12-20 09:08
I close this issue and propose https://github.com/GUDHI/TDA-tutorial/pull/77 to help the users to use the new interface

**Closed by VincentRouvreau** 2024-12-20 09:08 UTC
