### ISSUE TITLE
Strange-looking bibtex entry

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#591] opened 2022-03-22 19:49 UTC
![biblio](https://user-images.githubusercontent.com/10097863/159563488-296910a4-0915-401c-8b85-e3e27d4f91b4.png)

The entry for Garland Heckbert in the bibliography currently looks strange.

Reported to doxygen at https://github.com/doxygen/doxygen/issues/9344

**Comment by albert-github** [comment] 2022-05-18 10:50
I've just pushed a proposed patch, pull request doxygen/doxygen#9345

**Comment by albert-github** [comment] 2022-05-18 11:04
**a bit off-topic** for this issue:

Based on this issue I was interested in building the GUDHI documentation and see what kind of problems there are, on the doxygen side, in the GUDHI documentation.
Looking at e.g.  https://gudhi.inria.fr/doc/latest/dir_d44c64559bbebec7f509842c48db8b23.html I saw:

![image](https://user-images.githubusercontent.com/5223533/169022735-b0851580-cff3-4554-afcc-4c6451e81695.png)

which is probably due to an old version of the used footer for the HTML Page.

I forked and cloned the repository `gudhi-devel` and I also did the `git submodule update --init` and tried to run CMake but this failed as I don't have Boost (and I'm only interested in the documentation, so no intention of installing Boost).

- What is the best way to generate the documentation

(Note: In the CGAL project there is e.g the possibility `cmake ../Documentation/doc` so that just the documentation can be build and afterward I can run `make doc && make doc` or even just one manual with some special targets).

**Comment by mglisse** [comment] 2022-05-18 12:09
I think if you edit `src/cmake/modules/GUDHI_third_party_libraries.cmake` and remove the word `FATAL_ERROR` on line 7, then it is likely to work (after running cmake, you want `make doxygen`).

**Comment by albert-github** [comment] 2022-05-18 12:15
Thanks, I'll give it a try.

Now the process gets a bit further, but stops at a problem with QT, but I will look into it (as I have a QT version lying around at a non default place).

**Comment by albert-github** [comment] 2022-05-18 12:25
Thanks Marc.
I now succeeded in finishing the CMake step, in `src/GudhUI/CMakeLists.txt` I rep[laced on line 6 `if (OPENGL_FOUND)` by `if (OPENGL_FOUND1)`.
I can now run `make doxygen` (well in my case `nmake doxygen`).

So now I can start to do some tests and suggest some improvements etc.

**Comment by VincentRouvreau** [comment] 2022-05-20 08:26
> **a bit off-topic** for this issue:
> 
> Based on this issue I was interested in building the GUDHI documentation and see what kind of problems there are, on the doxygen side, in the GUDHI documentation. Looking at e.g. https://gudhi.inria.fr/doc/latest/dir_d44c64559bbebec7f509842c48db8b23.html I saw:
> 
> ![image](https://user-images.githubusercontent.com/5223533/169022735-b0851580-cff3-4554-afcc-4c6451e81695.png)
> 
> which is probably due to an old version of the used footer for the HTML Page.

I created #613 for not to miss this point.

**Comment by albert-github** [comment] 2022-05-21 07:49
Code of doxygen/doxygen#9345 has been integrated in master version of doxygen on GitHub.

**Comment by VincentRouvreau** [comment] 2022-09-16 14:20
Tested with conda package doxygen 1.9.5 and I can confirm it is fixed by https://github.com/doxygen/doxygen/pull/9345 
![Screenshot from 2022-09-16 16-15-49](https://user-images.githubusercontent.com/10407034/190660982-0995eaba-c41d-4938-bb84-fa2e087f621e.png).
As #699 advises to use doxygen 1.9.5, I close the issue.

**Closed by VincentRouvreau** 2022-09-16 14:20 UTC
